name: Create Release ZIP and Draft

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install zip
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
      - name: Create ZIP Archive
        run: |
          version=$(echo "${{ github.ref }}" | sed 's/refs\/tags\/v//')
          zip -r "copy-v$version.zip" . -x "*.git/*" -x "*.github/*"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "copy-${{ github.ref_name }}.zip"
          tag: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: "See the assets to download this version and install."
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
